### ISSUE TITLE
Crashed when opening

### ISSUE THREAD

**Issue by ghost** [HashEngineeringSolutions/dash-wallet#1]
## Expected Behavior

App starts up.
## Current Behavior

Immediate crashes\closes
## Possible Solution

Don't know.

## Steps to Reproduce (for bugs)

1. Press the app icon.
2. Done.

## Context

My accomplishment is interacting with the app.

## Your Environment

* Version used: 7.3.1 fdroid
* Environment name and version (e.g. Chrome 39, node.js 5.4): ??
* Operating System and version (desktop, server, or mobile): Android 11
* Link to your project: ??

**Comment by anarchotaoist** [comment]
This affects me also. Uninstalling and reinstalling did not fix it either.

**Comment by ghost** [comment]
Recent update fixed the bug on my device.

**Comment by anarchotaoist** [comment]
I can confirm a fix also - but I had to enter my 12 word passphrase and re-sync.
