### ISSUE TITLE
After Rom update app freezes on Splash Screen

### ISSUE THREAD

**Issue by anarchotaoist** [HashEngineeringSolutions/dash-wallet#2]
## Expected Behavior
After updating my rom - LineageOS for Microg - I expect Dash Wallet to retain information/configuration and open as before.

## Current Behavior
After updating my rom - LineageOS for Microg - the Dash Wallet app opens to the splash screen and freezes.

## CURRENT 'Solution'
Clear storage/cache, enter 12 word recovery and download the blockchain

## Steps to Reproduce (for bugs)

1. Update rom - LineageOS for Microg 
2. Open Dash Wallet
3. See splash screen with no login option

## Your Environment

* Version used: F-Droid version 7.3.2
* Operating System and version (desktop, server, or mobile):  LineageOS for Microg 18.1 on Oneplus 8T

**Comment by HashEngineering** [comment]
Sorry, we have upgraded a few times and are not sure if this is resolved.
