### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [HashEngineeringSolutions/dash-wallet#4]
...as https://github.com/HashEngineeringSolutions/dash-wallet/blob/v10.0.0-foss/integrations/coinbase/build.gradle#L60 depends on non-FOSS https://github.com/Kotlin/kotlinx.coroutines/blob/1.6.4/integration/kotlinx-coroutines-play-services/build.gradle.kts#L11

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/5e76a890bd31d7cc5829181efddd5ec92c5b1fd8

**Comment by HashEngineering** [comment]
Thank you.  I will review this.

**Comment by HashEngineering** [comment]
@licaon-kter 
I have removed the non-FOSS components and add another tag soon.

**Comment by HashEngineering** [comment]
@licaon-kter 
These lines should not be necessary after removing non-FOSS components in the coinbase module:

https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/hashengineering.darkcoin.wallet.yml?ref_type=heads#L160-164

**Comment by HashEngineering** [comment]
I created an issue in fdroiddata as well:  https://gitlab.com/fdroid/fdroiddata/-/issues/3152

**Comment by HashEngineering** [comment]
Version 10.0.1 is now on F-droid
